version: "3.9"
services:
  secret-network:
    image: enigmampc/secret-network-sw-dev
    container_name: secret-network
    volumes:
      - ./contract:/root/code
    ports:
      - 26656:26656
      - 1337:1337

  webapp:
    build: ./webapp
    ports:
      - 8000:80
